language: bash
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - python-docutils
    - shellcheck

before_install:
  - export PREFIX=$HOME/opt
  - mkdir -p $PREFIX/bin
  - export PATH=$PREFIX/bin:$PATH

before_script:
  - ./configure && make
  - cat compiled/install && compiled/install

script:
 - shellcheck butt

matrix:
  fast_finish: true
